---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml
  tags: vars

- name: INSTALL git packages
  package:
    name:
      - "{{ git }}"
      - "{{ git-flow }}"
