---
- name: INSTALL package - setvtrgb
  package:
    name:
      - kbd
    state: latest

- name: REGISTER which setvtrgb
  command: which setvtrgb
  register: which_setvtrgb

- name: TOUCH system color directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ color_dir }}"
    - "{{ color_dir }}/vtrgb"

- name: INSTALL vtrgb colorschemes
  copy:
    src: "{{ item }}"
    dest: "{{ color_dir }}/vtrgb/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - monochrome.vtrgb
    - bright.vtrgb

- name: LINK colorscheme.vtrgb /etc/vtrgb
  file:
    src: "{{ color_dir }}/vtrgb/{{ colorscheme }}.vtrgb"
    dest: /etc/vtrgb
    state: link
    force: yes

- name: INSTALL systemd unit - setvtrgb.service
  template:
    src: setvtrgb.service.j2
    dest: /usr/lib/systemd/system/setvtrgb.service
    owner: root
    group: root
    mode: 0644

- name: SYSTEMD enable - setvtrgb.service
  service:
    name: setvtrgb.service
    enabled: yes

- name: INSTALL color test scripts
  copy:
    src: "{{ item }}"
    dest: "{{ prefix }}/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - colortest
    - 256colortest
