- name: configure shell-agnostic environment
  connection: ssh
  gather_facts: true
  become: yes
  become_method: sudo
  hosts: default
  roles:
    - common
    - xdg

- name: configure ZSH
  connection: ssh
  gather_facts: true
  become: yes
  become_method: sudo
  hosts: default
  roles:
    - role: zsh
      vars:
        zsh_users:
            - vagrant
            - root
        zsh_plugins:
            - git
            - fd
            - fzf
            - ripgrep
            - fasd
