---
- name: set distro-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'

- name: INSTALL termbox.map
  copy:
    src: termbox.map
    dest: "{{ keymaps_dir }}"
    owner: root
    group: root
    mode: 0644
